--------------------------------------------------------
--  File created - Thursday-May-30-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADMIN" 
   (	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ANS" 
   (	"QID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"ANS" LONG, 
	"POST_TIME" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FAQ
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FAQ" 
   (	"QID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"QUESTION" VARCHAR2(255 BYTE), 
	"DESCRIPTION" LONG, 
	"POST_TIME" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MEMBER" 
   (	"USERNAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(30 BYTE) DEFAULT 'newchef', 
	"PROFILE_PIC" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_BOOK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORDER_BOOK" 
   (	"RECIPE_ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"BOOK_ID" NUMBER(*,0), 
	"BKASH_NO" VARCHAR2(50 BYTE), 
	"ACTIVE" NUMBER(*,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECIPE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RECIPE" 
   (	"RECIPE_ID" NUMBER(*,0), 
	"CATEGORY" VARCHAR2(255 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"PHOTO" VARCHAR2(255 BYTE), 
	"RATING" FLOAT(126), 
	"ENGRADIENTS" VARCHAR2(255 BYTE), 
	"PROCEDURE" LONG, 
	"DATETIME" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECIPE_BOOKS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RECIPE_BOOKS" 
   (	"BOOK_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" LONG, 
	"WRITTER" VARCHAR2(255 BYTE), 
	"PRICE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECIPE_BOX
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RECIPE_BOX" 
   (	"USERNAME" VARCHAR2(30 BYTE), 
	"RECIPE_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECIPE_EVENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RECIPE_EVENT" 
   (	"EVENT_ID" NUMBER(*,0), 
	"EVENT_NAME" VARCHAR2(255 BYTE), 
	"CATEGORY" VARCHAR2(255 BYTE), 
	"DESCRIPTION" LONG, 
	"DEADLINE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_RECIPE_EVENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USER_RECIPE_EVENT" 
   (	"USERNAME" VARCHAR2(30 BYTE), 
	"EVENT_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"PHOTO" VARCHAR2(255 BYTE), 
	"ENGRADIENTS" VARCHAR2(255 BYTE), 
	"PROCEDURE" LONG, 
	"RATING" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WINNER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."WINNER" 
   (	"USERNAME" VARCHAR2(30 BYTE), 
	"EVENT_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ADMIN
SET DEFINE OFF;
Insert into SYSTEM.ADMIN (USERNAME,PASSWORD) values ('admin','1234');
REM INSERTING into SYSTEM.ANS
SET DEFINE OFF;
REM INSERTING into SYSTEM.FAQ
SET DEFINE OFF;
REM INSERTING into SYSTEM.MEMBER
SET DEFINE OFF;
Insert into SYSTEM.MEMBER (USERNAME,EMAIL,PASSWORD,STATUS,PROFILE_PIC) values ('farhan','far@gmail.com','1234',null,null);
Insert into SYSTEM.MEMBER (USERNAME,EMAIL,PASSWORD,STATUS,PROFILE_PIC) values ('sujon','depessimist@gmail.com','e10adc3949ba59abbe56e057f20f883e','newchef',null);
Insert into SYSTEM.MEMBER (USERNAME,EMAIL,PASSWORD,STATUS,PROFILE_PIC) values ('admin','noyon3237@yahoo.com','81dc9bdb52d04dc20036dbd8313ed055','newchef',null);
Insert into SYSTEM.MEMBER (USERNAME,EMAIL,PASSWORD,STATUS,PROFILE_PIC) values ('another','sujon335@yahoo.com','81dc9bdb52d04dc20036dbd8313ed055','newchef',null);
Insert into SYSTEM.MEMBER (USERNAME,EMAIL,PASSWORD,STATUS,PROFILE_PIC) values ('sunlight0905056','ahmed_faysal77@yahoo.com','e10adc3949ba59abbe56e057f20f883e','newchef',null);
Insert into SYSTEM.MEMBER (USERNAME,EMAIL,PASSWORD,STATUS,PROFILE_PIC) values ('hudai3','binotaroy13@gmail.com','e10adc3949ba59abbe56e057f20f883e','newchef',null);
Insert into SYSTEM.MEMBER (USERNAME,EMAIL,PASSWORD,STATUS,PROFILE_PIC) values ('ranarhall','ssudiptosaha@outlook.com','e10adc3949ba59abbe56e057f20f883e','newchef',null);
Insert into SYSTEM.MEMBER (USERNAME,EMAIL,PASSWORD,STATUS,PROFILE_PIC) values ('c_maksud','khaled.buetme10@gmail.com','e10adc3949ba59abbe56e057f20f883e','newchef',null);
REM INSERTING into SYSTEM.ORDER_BOOK
SET DEFINE OFF;
REM INSERTING into SYSTEM.RECIPE
SET DEFINE OFF;
Insert into SYSTEM.RECIPE (RECIPE_ID,CATEGORY,TITLE,PHOTO,RATING,ENGRADIENTS,PROCEDURE,DATETIME) values (8,'uiyiuyiu','jgjhgjhgj','/img/Image092.gif',0,'hgjgjhgjg','opopoioi',to_timestamp('30-MAY-13 02.46.30.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'));
Insert into SYSTEM.RECIPE (RECIPE_ID,CATEGORY,TITLE,PHOTO,RATING,ENGRADIENTS,PROCEDURE,DATETIME) values (9,'dgdfgdf','dfgdfgdfg','/img/206384_142558295814187_100001800537225_255638_7661010_n.jpg',0,'dfgdfg','dfgdfgdfg',to_timestamp('30-MAY-13 02.47.19.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'));
Insert into SYSTEM.RECIPE (RECIPE_ID,CATEGORY,TITLE,PHOTO,RATING,ENGRADIENTS,PROCEDURE,DATETIME) values (7,'uiyiuyiu','jgjhgjhgj','/img/Image092.gif',0,'hgjgjhgjg','opopoioi',to_timestamp('30-MAY-13 02.45.39.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'));
REM INSERTING into SYSTEM.RECIPE_BOOKS
SET DEFINE OFF;
Insert into SYSTEM.RECIPE_BOOKS (BOOK_ID,TITLE,DESCRIPTION,WRITTER,PRICE) values (1000,'notun ghora','amsfvadfnsdvnbfvsdnbvfnsdbvfnsdvfnsdvbfnbnsmndbfmnsdbmnfbsdmnbfsdmnbfmsdf','jana nei','120');
Insert into SYSTEM.RECIPE_BOOKS (BOOK_ID,TITLE,DESCRIPTION,WRITTER,PRICE) values (1001,'notun ghora','amsfvadfnsdvnbfvsdnbvfnsdbvfnsdvfnsdvbfnbnsmndbfmnsdbmnfbsdmnbfsdmnbfmsdf','jana nei','120');
REM INSERTING into SYSTEM.RECIPE_BOX
SET DEFINE OFF;
REM INSERTING into SYSTEM.RECIPE_EVENT
SET DEFINE OFF;
REM INSERTING into SYSTEM.USER_RECIPE_EVENT
SET DEFINE OFF;
REM INSERTING into SYSTEM.WINNER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007503
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007503" ON "SYSTEM"."ADMIN" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007524
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007524" ON "SYSTEM"."FAQ" ("QID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007502
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007502" ON "SYSTEM"."MEMBER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007514
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007514" ON "SYSTEM"."ORDER_BOOK" ("RECIPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007507
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007507" ON "SYSTEM"."RECIPE" ("RECIPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007510
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007510" ON "SYSTEM"."RECIPE_BOOKS" ("BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007518
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007518" ON "SYSTEM"."RECIPE_EVENT" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADMIN" ADD PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAQ
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FAQ" ADD PRIMARY KEY ("QID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."FAQ" MODIFY ("QID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MEMBER" ADD PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_BOOK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORDER_BOOK" ADD PRIMARY KEY ("RECIPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ORDER_BOOK" MODIFY ("RECIPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECIPE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RECIPE" ADD PRIMARY KEY ("RECIPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."RECIPE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RECIPE" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RECIPE" MODIFY ("RECIPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECIPE_BOOKS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RECIPE_BOOKS" ADD PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."RECIPE_BOOKS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RECIPE_BOOKS" MODIFY ("BOOK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECIPE_EVENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RECIPE_EVENT" ADD PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."RECIPE_EVENT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ANS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANS" ADD FOREIGN KEY ("QID")
	  REFERENCES "SYSTEM"."FAQ" ("QID") ENABLE;
  ALTER TABLE "SYSTEM"."ANS" ADD FOREIGN KEY ("USERNAME")
	  REFERENCES "SYSTEM"."MEMBER" ("USERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAQ
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FAQ" ADD FOREIGN KEY ("USERNAME")
	  REFERENCES "SYSTEM"."MEMBER" ("USERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_BOOK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORDER_BOOK" ADD FOREIGN KEY ("USERNAME")
	  REFERENCES "SYSTEM"."MEMBER" ("USERNAME") ENABLE;
  ALTER TABLE "SYSTEM"."ORDER_BOOK" ADD FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SYSTEM"."RECIPE_BOOKS" ("BOOK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECIPE_BOX
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RECIPE_BOX" ADD FOREIGN KEY ("USERNAME")
	  REFERENCES "SYSTEM"."MEMBER" ("USERNAME") ENABLE;
  ALTER TABLE "SYSTEM"."RECIPE_BOX" ADD FOREIGN KEY ("RECIPE_ID")
	  REFERENCES "SYSTEM"."RECIPE" ("RECIPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_RECIPE_EVENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USER_RECIPE_EVENT" ADD FOREIGN KEY ("USERNAME")
	  REFERENCES "SYSTEM"."MEMBER" ("USERNAME") ENABLE;
  ALTER TABLE "SYSTEM"."USER_RECIPE_EVENT" ADD FOREIGN KEY ("EVENT_ID")
	  REFERENCES "SYSTEM"."RECIPE_EVENT" ("EVENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WINNER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."WINNER" ADD FOREIGN KEY ("USERNAME")
	  REFERENCES "SYSTEM"."MEMBER" ("USERNAME") ENABLE;
  ALTER TABLE "SYSTEM"."WINNER" ADD FOREIGN KEY ("EVENT_ID")
	  REFERENCES "SYSTEM"."RECIPE_EVENT" ("EVENT_ID") ENABLE;
